In [1]:
import pandas as pd
import numpy as np

In [2]:
vader_df = pd.read_excel(r"C:\Users\sawanta\OneDrive - Dun and Bradstreet\Desktop\News\Old Method(VADER)\NewsAndSentiment_04112022.xlsx")
spacy_df = pd.read_excel(r"C:\Users\sawanta\OneDrive - Dun and Bradstreet\Desktop\News\New Method(SPACY)\NewsandSentimentsAnalysis_04112022.xlsx")

In [3]:
# News Fraudulent Word Tagging
words=["fraud", "conspiracy", "cheating", "forgery", "false evidence", "fake evidence", "breach of trust", "money laundering", 
       "corrupt", "abetment","scam", "helped in crime", "helped in criminal", "extortion", "warrants pending", "warrant pending", 
       "sexual harassment", "fraudulent", "corruption", "delay in payment", "delayed payment", "cheque bounce", "bounced cheque", 
       "loan due", "taxes due", "liquidation", "winding up", "bankruptcy", "bankrupt", "debarred", "balcklisted","labor issues", 
       "labour issues", "child labour", "child labor", "forced labor", "forced labour", "GMP audit observation", 
       "drt", "debt recovery tribunal", "debt recovery","gst evasion","gst"]

# Define the function which takes a string and a list of words to extract as inputs
def listing_splitter(text, word):
    # Try except to handle np.nans in input
    try:
        # Extract the list of flags
        flags = [l for l in words if l in text.lower()]
        # If any flags were extracted then return the list
        if flags:
            return flags
        # Otherwise return np.nan
        else:
            return np.nan
    except AttributeError:
        return np.nan

# Apply the function to the column
vader_df['Test_Flag'] = vader_df['News_neg_wrds'].apply(lambda x: listing_splitter(x, words))
vader_df

,Date,URL,Category,Headline,Headline_sentiment,Headline_senti_score,Headline_pos_wrds,Headline_neu_wrds,Headline_neg_wrds,News,News_sentiment,News_senti_score,News_key_phrases,News_pos_wrds,News_neu_wrds,News_neg_wrds,Words,Test_Flag
0,04-11-2022,https://economictimes.indiatimes.com/markets/s...,markets/stocks,Titan Q2 Results: Profit rises 34% YoY to Rs 8...,Positive,0.7783,"profit,optimistic,growth","titan,q2,results,:,rises,34,%,yoy,to,rs,857,cr...",NaN,titan on friday reported a 34% year-on-year (y...,Positive,0.9903,"titan,% year-on-year,yoy,net profit,september,...","profit,increased,growth,care,interest,festive,...","titan,on,friday,reported,a,34,%,year-on-year,(...","beating,uncertain",NaN,NaN
1,04-11-2022,https://economictimes.indiatimes.com/industry/...,industry/cons-products,"Reliance plans to enter salon business, may bu...",Neutral,0.0000,NaN,"reliance,plans,to,enter,salon,business,,,may,b...",NaN,reliance retail is set to enter the salon busi...,Positive,0.9817,"reliance,salon business,chennai-based naturals...","help,beauty,robust,opportunities,securities,ag...","reliance,retail,is,set,to,enter,the,salon,busi...","worst,not",NaN,NaN
2,04-11-2022,https://economictimes.indiatimes.com/markets/s...,markets/stocks,Cipla Q2 Results: Profit rises 11% YoY to Rs 7...,Positive,0.4404,profit,"cipla,q2,results,:,rises,11,%,yoy,to,rs,789,cr...",NaN,pharma major cipla on friday reported a 10.9% ...,Positive,0.8325,"pharma,cipla,% year-on-year,yoy,september,net ...","profit,increased,improved","pharma,major,cipla,on,friday,reported,a,10.9,%...","against,loss",NaN,NaN
3,04-11-2022,https://economictimes.indiatimes.com/markets/s...,markets/stocks,"Is Nifty fairly valued at 18,000? Study these ...",Positive,0.7244,"valued,3","is,nifty,fairly,at,18,000,?,study,these,indica...",NaN,new delhi: helped by buying by fiis for six co...,Positive,0.9914,"new delhi,helped,fiis,consecutive days,fed,nif...","hoping,securities,valued,3,value,attractive,im...","new,delhi,:,helped,by,buying,fiis,for,six,cons...","troubling,against,no,not",NaN,NaN
4,04-11-2022,https://economictimes.indiatimes.com/news/econ...,news/economy,EU financial regulators disqualify 6 Indian co...,Neutral,0.0000,NaN,"eu,financial,regulators,disqualify,6,indian,co...",NaN,"over the last 48 hours, all european banks in ...",Positive,0.9835,"european banks,india,european union,financial ...","like,significant,securities,comfortable,respec...","over,the,last,48,hours,,,all,european,banks,in...","limited,not,no,fail,strike,disqualified,disadv...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,04-11-2022,https://timesofindia.indiatimes.com/world/paki...,/world,Imran Khan's party to hold nationwide protests...,Positive,0.2023,party,"imran,khan,'s,to,hold,nationwide,on,friday",protests,"""sezxj hide\n ""_2sdar contentwrappe",Negative,-0.1779,"sezxj hide,_2sdar contentwrapper",NaN,"``,sezxj,_2sdar,contentwrapper",hide,NaN,NaN
255,04-11-2022,https://timesofindia.indiatimes.com/auto/news/...,/auto/news,"Check petrol and diesel price in Delhi, Mumbai...",Neutral,0.0000,NaN,"check,petrol,and,diesel,price,in,delhi,,,mumba...",NaN,"""sezxj hide\n ""_2sdar contentwrappe",Negative,-0.1779,"sezxj hide,_2sdar contentwrapper",NaN,"``,sezxj,_2sdar,contentwrapper",hide,NaN,NaN
256,04-11-2022,https://timesofindia.indiatimes.com/auto/news/...,/auto/news,Hero Moto tech partner Gogoro to launch batter...,Positive,0.6249,"hero,launch","moto,tech,partner,gogoro,to,battery-swapping,s...",NaN,"""sezxj hide\n ""_2sdar contentwrappe",Negative,-0.1779,"sezxj hide,_2sdar contentwrapper",NaN,"``,sezxj,_2sdar,contentwrapper",hide,NaN,NaN
257,04-11-2022,https://timesofindia.indiatimes.com/india/pm-m...,/india,PM Modi to attend first in-person Quad summit ...,Neutral,0.0000,NaN,"pm,modi,to,attend,first,in-person,quad,summit,...",NaN,"""sezxj hide\n ""_2sdar contentwrappe",Negative,-0.1779,"sezxj hide,_2sdar contentwrapper",NaN,"``,sezxj,_2sdar,contentwrapper",hide,NaN,NaN
258,04-11-2022,https://timesofindia.indiatimes.com/gadgets-ne...,/gadgets-news,Vivo Y55s budget smartphone tipped to launch o...,Negative,-0.2023,launch,"vivo,y55s,budget,smartphone,tipped,to,on,this,...",leaked,"""sezxj hide\n ""_2sdar contentwrappe",Negative,-0.1779,"sezxj hide,_2sdar contentwrapper",NaN,"``,sezxj,_2sdar,contentwrapper",hide,NaN,NaN

In [4]:
df = pd.merge(vader_df, spacy_df, on = 'URL', how = 'left' )
df

,Date_x,URL,Category_x,Headline_x,Headline_sentiment,Headline_senti_score,Headline_pos_wrds,Headline_neu_wrds,Headline_neg_wrds,News_x,...,Words,Test_Flag_x,Date_y,Category_y,Headline_y,News_y,Clean_text,Test_Flag_y,Compound,Sentiment
0,04-11-2022,https://economictimes.indiatimes.com/markets/s...,markets/stocks,Titan Q2 Results: Profit rises 34% YoY to Rs 8...,Positive,0.7783,"profit,optimistic,growth","titan,q2,results,:,rises,34,%,yoy,to,rs,857,cr...",NaN,titan on friday reported a 34% year-on-year (y...,...,NaN,NaN,04-11-2022,markets/stocks,Titan Q2 Results: Profit rises 34% YoY to Rs 8...,Titan on Friday reported a 34% year-on-year (Y...,titan friday reported 34% year-on-year (yoy) r...,NaN,0.075884,1.0
1,04-11-2022,https://economictimes.indiatimes.com/industry/...,industry/cons-products,"Reliance plans to enter salon business, may bu...",Neutral,0.0000,NaN,"reliance,plans,to,enter,salon,business,,,may,b...",NaN,reliance retail is set to enter the salon busi...,...,NaN,NaN,04-11-2022,industry/cons-products,"Reliance plans to enter salon business, may bu...",Reliance Retail is set to enter the salon busi...,reliance retail set enter salon business talks...,NaN,-0.073211,1.0
2,04-11-2022,https://economictimes.indiatimes.com/markets/s...,markets/stocks,Cipla Q2 Results: Profit rises 11% YoY to Rs 7...,Positive,0.4404,profit,"cipla,q2,results,:,rises,11,%,yoy,to,rs,789,cr...",NaN,pharma major cipla on friday reported a 10.9% ...,...,NaN,NaN,04-11-2022,markets/stocks,Cipla Q2 Results: Profit rises 11% YoY to Rs 7...,Pharma major Cipla on Friday reported a 10.9% ...,pharma major cipla friday reported 10.9% year-...,NaN,0.070028,1.0
3,04-11-2022,https://economictimes.indiatimes.com/markets/s...,markets/stocks,"Is Nifty fairly valued at 18,000? Study these ...",Positive,0.7244,"valued,3","is,nifty,fairly,at,18,000,?,study,these,indica...",NaN,new delhi: helped by buying by fiis for six co...,...,NaN,NaN,04-11-2022,markets/stocks,"Is Nifty fairly valued at 18,000? Study these ...",NEW DELHI: Helped by buying by FIIs for six co...,new delhi: helped buying fiis consecutive days...,NaN,0.098516,1.0
4,04-11-2022,https://economictimes.indiatimes.com/news/econ...,news/economy,EU financial regulators disqualify 6 Indian co...,Neutral,0.0000,NaN,"eu,financial,regulators,disqualify,6,indian,co...",NaN,"over the last 48 hours, all european banks in ...",...,NaN,NaN,04-11-2022,news/economy,EU financial regulators disqualify 6 Indian co...,"Over the last 48 hours, all European banks in ...","48 hours, european banks india thrown quandary...",NaN,0.056152,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,04-11-2022,https://timesofindia.indiatimes.com/world/paki...,/world,Imran Khan's party to hold nationwide protests...,Positive,0.2023,party,"imran,khan,'s,to,hold,nationwide,on,friday",protests,"""sezxj hide\n ""_2sdar contentwrappe",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
258,04-11-2022,https://timesofindia.indiatimes.com/auto/news/...,/auto/news,"Check petrol and diesel price in Delhi, Mumbai...",Neutral,0.0000,NaN,"check,petrol,and,diesel,price,in,delhi,,,mumba...",NaN,"""sezxj hide\n ""_2sdar contentwrappe",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
259,04-11-2022,https://timesofindia.indiatimes.com/auto/news/...,/auto/news,Hero Moto tech partner Gogoro to launch batter...,Positive,0.6249,"hero,launch","moto,tech,partner,gogoro,to,battery-swapping,s...",NaN,"""sezxj hide\n ""_2sdar contentwrappe",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
260,04-11-2022,https://timesofindia.indiatimes.com/india/pm-m...,/india,PM Modi to attend first in-person Quad summit ...,Neutral,0.0000,NaN,"pm,modi,to,attend,first,in-person,quad,summit,...",NaN,"""sezxj hide\n ""_2sdar contentwrappe",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
261,04-11-2022,https://timesofindia.indiatimes.com/gadgets-ne...,/gadgets-news,Vivo Y55s budget smartphone tipped to launch o...,Negative,-0.2023,launch,"vivo,y55s,budget,smartphone,tipped,to,on,this,...",leaked,"""sezxj hide\n ""_2sdar contentwrappe",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df = df[['URL', 'News_x','News_sentiment', 'Sentiment', 'Test_Flag_x', 'Test_Flag_y']]
df= df.drop_duplicates(subset = 'News_x')
df

,URL,News_x,News_sentiment,Sentiment,Test_Flag_x,Test_Flag_y
0,https://economictimes.indiatimes.com/markets/s...,titan on friday reported a 34% year-on-year (y...,Positive,1.0,NaN,NaN
1,https://economictimes.indiatimes.com/industry/...,reliance retail is set to enter the salon busi...,Positive,1.0,NaN,NaN
2,https://economictimes.indiatimes.com/markets/s...,pharma major cipla on friday reported a 10.9% ...,Positive,1.0,NaN,NaN
3,https://economictimes.indiatimes.com/markets/s...,new delhi: helped by buying by fiis for six co...,Positive,1.0,NaN,NaN
4,https://economictimes.indiatimes.com/news/econ...,"over the last 48 hours, all european banks in ...",Positive,1.0,NaN,NaN
...,...,...,...,...,...,...
221,https://www.livemint.com//companies/news/ge-ae...,ge aerospace and tata advanced systems ltd hav...,Positive,NaN,NaN,NaN
222,https://www.livemint.com//news/india/delhi-air...,thick smog blanketed delhi on friday as the ci...,Negative,NaN,NaN,NaN
223,https://www.livemint.com//companies/company-re...,"interglobe aviation, the parent company of air...",Negative,NaN,NaN,NaN
224,https://www.livemint.com//news/india/caqm-meet...,new delhi: commission for air quality manageme...,Negative,NaN,NaN,NaN
225,https://timesofindia.indiatimes.com/world/paki...,"""sezxj hide\n ""_2sdar contentwrappe",Negative,0.0,NaN,NaN

In [6]:
negative =df.loc[df['News_sentiment']=='Negative']
len(negative)

45

In [7]:
vader_df = vader_df[['Date', 'URL', 'Category', 'Headline', 'News', 'News_sentiment', 'News_senti_score', 'Test_Flag']]
tvader_df = vader_df.dropna(subset = 'Test_Flag')
tvader_df

,Date,URL,Category,Headline,News,News_sentiment,News_senti_score,Test_Flag
5,04-11-2022,https://economictimes.indiatimes.com/markets/s...,markets/stocks,GAIL Q2 Results: Profit tumbles 46% YoY to Rs ...,new delhi: state-owned gas utility gail (india...,Positive,0.8910,[bankrupt]
22,04-11-2022,https://economictimes.indiatimes.com/industry/...,industry/banking,Reliance Capital lenders to meet on Friday to ...,lenders of debt-ridden reliance capital ltd (r...,Negative,-0.9451,"[bankruptcy, bankrupt]"
64,04-11-2022,https://economictimes.indiatimes.com/markets/c...,markets/cryptocurrency,Why the next decade belongs to DeFi and will s...,while the global investor community was latchi...,Positive,0.9534,[fraud]
65,04-11-2022,https://economictimes.indiatimes.com/markets/c...,markets/cryptocurrency,Annual tech gathering takes aim at crypto,one of the world's biggest technology get-toge...,Positive,0.7964,[scam]
70,04-11-2022,https://economictimes.indiatimes.com/markets/c...,markets/cryptocurrency,Crypto Price Today Live: Bitcoin holds $20K; S...,new delhi: major crypto tokens slipped on frid...,Positive,0.7962,[scam]
120,04-11-2022,https://www.business-standard.com//article/eco...,economy-policy,"""How IBBIs tighter compliance rules for resol...",the insolvency and bankruptcy board of indiars...,Positive,0.9991,"[bankruptcy, bankrupt]"

In [8]:
tspacy_df = spacy_df.dropna(subset = 'Test_Flag')
tspacy_df

,Date,URL,Category,Headline,News,Clean_text,Test_Flag,Compound,Sentiment
6,04-11-2022,https://economictimes.indiatimes.com/industry/...,industry/banking,Reliance Capital lenders divided over 'Challen...,The Committee of Creditors (CoC) of debt-ridde...,committee creditors (coc) debt-ridden reliance...,bankruptcy,-0.041626,0
9,04-11-2022,https://economictimes.indiatimes.com/markets/s...,markets/stocks,GAIL Q2 Results: Profit tumbles 46% YoY to Rs ...,New Delhi: State-owned gas utility GAIL (India...,new delhi: state-owned gas utility gail (india...,bankrupt,0.016196,0
28,04-11-2022,https://economictimes.indiatimes.com/industry/...,industry/banking,Reliance Capital lenders to meet on Friday to ...,Lenders of debt-ridden Reliance Capital Ltd (R...,lenders debt-ridden reliance capital ltd (rcl)...,bankruptcy,0.024072,0
47,04-11-2022,https://economictimes.indiatimes.com/markets/c...,markets/cryptocurrency,Sitharaman's call for G-20 nation to regulate ...,New Delhi: Union Finance Minister Nirmala Sith...,new delhi: union finance minister nirmala sith...,money laundering,0.086771,1
59,04-11-2022,https://economictimes.indiatimes.com/markets/c...,markets/cryptocurrency,Why the next decade belongs to DeFi and will s...,While the global investor community was latchi...,global investor community latching crypto band...,fraud,0.073628,1
...,...,...,...,...,...,...,...,...,...
257,04-11-2022,https://www.moneycontrol.com/news/business/mah...,/business,Kalyan Dombivali Civic Body issues notices to...,The Kalyan Dombivali Municipal Corporation (KD...,kalyan dombivali municipal corporation (kdmc) ...,fraud,0.060689,1
260,04-11-2022,https://www.moneycontrol.com/news/business/per...,/business,Income-tax deductions on home loans made easy:...,The end of financial year 2022-23 is a few mon...,"end financial year 2022-23 months away soon, s...",gst,0.074736,1
274,04-11-2022,https://www.moneycontrol.com/news/business/per...,/business,Income-tax deductions on home loans made easy:...,The end of financial year 2022-23 is a few mon...,"end financial year 2022-23 months away soon, s...",gst,0.074736,1
279,04-11-2022,https://www.moneycontrol.com/news/business/per...,/business,Five things you should consider before choosin...,While India celebrates festivals round the yea...,"india celebrates festivals round year, indian ...",fraud,0.083333,1
306,04-11-2022,https://www.moneycontrol.com/news/business/mar...,/business,"Taking Stock |Sensex up 114 points, Nifty abov...",The Indian market closed in the green after a ...,indian market closed green volatile session no...,gst,0.064797,1

In [9]:
print(len(tvader_df))

6

In [10]:
print(len(tspacy_df))

96

In [11]:
neg_to_pos= df[(df['News_sentiment']=='Negative') & (df['Sentiment']==1)]
neg_to_pos

,URL,News_x,News_sentiment,Sentiment,Test_Flag_x,Test_Flag_y
8,https://economictimes.indiatimes.com/small-biz...,one of the world’s biggest shipping companies ...,Negative,1.0,NaN,NaN
45,https://economictimes.indiatimes.com/markets/s...,global brokerage firm goldman sachs maintained...,Negative,1.0,NaN,NaN
57,https://economictimes.indiatimes.com/markets/c...,"niagara falls, united states, nov 2, 2022 -in ...",Negative,1.0,NaN,NaN
77,https://economictimes.indiatimes.com/small-biz...,new delhi: india's iron ore exports dropped to...,Negative,1.0,NaN,NaN
80,https://economictimes.indiatimes.com/small-biz...,"san francisco: a few months ago, makers of com...",Negative,1.0,NaN,NaN
101,https://economictimes.indiatimes.com/markets/s...,indian market is expected to open flat on wedn...,Negative,1.0,NaN,NaN
112,https://economictimes.indiatimes.com/small-biz...,inflationary pressures in the us simmered down...,Negative,1.0,NaN,NaN
139,https://www.business-standard.com//article/cur...,"""_x000D_\n\t_x000D_\n\t\twith delhi&#39;s air ...",Negative,1.0,NaN,NaN
197,https://www.livemint.com//market/mark-to-marke...,the much-awaited federal open market committee...,Negative,1.0,NaN,NaN
201,https://www.livemint.com//market/mark-to-marke...,indigo paints ltd reported better-than-expecte...,Negative,1.0,NaN,NaN
211,https://www.livemint.com//companies/news/warne...,david zaslav declared it a “bright shiny day’’...,Negative,1.0,NaN,NaN

In [12]:
len(neg_to_pos)

11

In [13]:
neg_to_neu= df[(df['News_sentiment']=='Negative') & (df['Sentiment']==0)]
neg_to_neu

,URL,News_x,News_sentiment,Sentiment,Test_Flag_x,Test_Flag_y
15,https://economictimes.indiatimes.com/news/econ...,the directorate general of trade remedies (dgt...,Negative,0.0,NaN,NaN
16,https://economictimes.indiatimes.com/news/econ...,the fall in the indian rupee's forward premium...,Negative,0.0,NaN,NaN
22,https://economictimes.indiatimes.com/industry/...,lenders of debt-ridden reliance capital ltd (r...,Negative,0.0,"[bankruptcy, bankrupt]",bankruptcy
79,https://economictimes.indiatimes.com/small-biz...,europe is close to entering a recession and th...,Negative,0.0,NaN,NaN
85,https://economictimes.indiatimes.com/small-biz...,the world has lately been confronted with one ...,Negative,0.0,NaN,NaN
87,https://economictimes.indiatimes.com/small-biz...,costs for shipping energy are surging as europ...,Negative,0.0,NaN,NaN
88,https://economictimes.indiatimes.com/small-biz...,"arques, france: the furnace, heated to 1,500 d...",Negative,0.0,NaN,NaN
90,https://economictimes.indiatimes.com/industry/...,private sector dcb bank has revised upwards th...,Negative,0.0,NaN,NaN
110,https://economictimes.indiatimes.com/news/econ...,rice sowing in the current kharif season has d...,Negative,0.0,NaN,NaN
208,https://www.livemint.com//market/sec-accountan...,wall street’s top watchdog is warning that the...,Negative,0.0,NaN,NaN
217,https://www.livemint.com/news/india/mumbai-loc...,mumbai local train services on friday were dis...,Negative,0.0,NaN,NaN
218,https://www.livemint.com/technology/tech-news/...,twitter users across the world are facing trou...,Negative,0.0,NaN,NaN
225,https://timesofindia.indiatimes.com/world/paki...,"""sezxj hide\n ""_2sdar contentwrappe",Negative,0.0,NaN,NaN

In [14]:
len(neg_to_neu)

13

In [15]:
tneg_to_pos = neg_to_pos.dropna(subset = 'Test_Flag_x')
tneg_to_pos

Empty DataFrame
Columns: [URL, News_x, News_sentiment, Sentiment, Test_Flag_x, Test_Flag_y]
Index: []

In [16]:
tneg_to_neu = neg_to_neu.dropna(subset = 'Test_Flag_x')
tneg_to_neu

,URL,News_x,News_sentiment,Sentiment,Test_Flag_x,Test_Flag_y
22,https://economictimes.indiatimes.com/industry/...,lenders of debt-ridden reliance capital ltd (r...,Negative,0.0,"[bankruptcy, bankrupt]",bankruptcy

In [17]:
df['Test_Flag_y'].explode().unique()

array([nan, 'bankrupt', 'bankruptcy', 'money laundering', 'fraud',
       'liquidation', 'gst', 'corrupt'], dtype=object)